[package]
name = "auth"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
postgres = "0.19.7"
#rocket = "0.4.11"
rocket = "=0.5.0-rc.3"
rocket_db_pools = { version = "0.1.0-rc.3", features = ["sqlx_postgres"] }
toml = "0.7.6"
